services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: dockerfile.yml
      args:
        - environment=Development
    container_name: todo_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

networks:
  default:
    driver: bridge
